version: '3'
services:
  app:
    build:
      context: .
      args:
        - enable_mecab=1
    platform: linux/amd64
    volumes:
      - './config.json:/ai-kor/config.json:ro'
      - './font.ttf:/ai-kor/font.ttf:ro'
      - './data:/ai-kor/data'
    restart: always
